cmake_minimum_required(VERSION 4.3)
project(untitled)

set(CMAKE_CXX_STANDARD 20)

add_executable(untitled main.cpp
        empleado.h
        empleado.cpp
        empleado.h
        desarrollador.h
        desarrollador.cpp
        tecnicoSoporte.h
        Administrador.h
        "Administrador .cpp"
        TecnicoSoporte.cpp
)
